name: TrialPunishment
version: '${project.version}'
main: me.dev.zennyel.TrialPunishment
authors: [ Zennyel ]
description: DevRoom trial punishment plugin, available on github!
website: https://github.com/guilherme-santiago07/
